FROM node:22-alpine3.22 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install --frozen-lockfile

COPY . .

RUN npm run prisma:generate

RUN npm run build

FROM node:22-alpine3.22 AS runner

WORKDIR /app

COPY --from=builder /app/package*.json ./

RUN npm install --omit=dev --frozen-lockfile

COPY --from=builder /app/dist ./dist

COPY --from=builder /app/node_modules/@prisma-app ./node_modules/@prisma-app

EXPOSE 8000

CMD ["npm", "start"]
